services:
  server:
    image: ohttp-server
    ports:
      - "9443:9443"
    network_mode: "host"
    environment:
      - TARGET=http://localhost:3000
    depends_on:
      - web_service

  web_service:
    image: nodejs-streaming
    network_mode: "host"
    ports:
      - "3000:3000"