services:
  server:
    image: ohttp-server
    ports:
      - "9443:9443"
    network_mode: "host"
    environment:
      - TARGET=http://localhost:8000
      - INSTANCE_SPECIFIC_KEY=1
    depends_on:
      - whisper

  whisper:
    image: fedirz/faster-whisper-server:latest-cuda
    network_mode: "host"
    ports:
      - "8000:8000"