[package]
name = "bhttp-convert"
version = "0.5.4"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2021"

[dependencies]
structopt = "0.3"

[dependencies.bhttp]
path= "../bhttp"
features = ["bhttp", "http"]
