[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
colored = "2.1.0"
hex = "0.4.3"
log = "0.4.22"
openssl = "0.10.66"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.63"
